language: node_js
node_js:
  - "10"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm install codecov -g
after_success:
  - codecov -f coverage/coverage-final.json
